### ISSUE TITLE
REST API?

### ISSUE THREAD

**Issue by ninjasort** [ActiveCampaign/example-add_subscriber_send_instant#1]
What if I'm not using PHP and just want to add a subscriber via a REST endpoint?

**Comment by mthommes** [comment]
Hello! Our [full documentation](http://www.activecampaign.com/api/overview.php) lists the REST endpoints. You can compare what we have in this PHP example to see the individual calls you would need to make.

**Comment by ninjasort** [comment]
There's no REST API at that link you sent. Could you point me to the exact
page with the end points? Thanks.

**Comment by mthommes** [comment]
Sorry about that. I updated the link on the web after submitting the comment, so your Github email notification likely has the wrong link. [Here is the correct link](http://www.activecampaign.com/api/overview.php).

**Comment by ninjasort** [comment]
I still don't see a base API url. The end points only show /admin/api Is it
just activecampaign.com? Also, is there any access token for the calls?

**Comment by mthommes** [comment]
The endpoint is listed per method:

![image 2016-08-09 at 10 32 51 am](https://cloud.githubusercontent.com/assets/634489/17522449/b5466f50-5e1c-11e6-9687-6c1ad1454e15.png)

To get your base API URL and key, that is available under the settings section of your ActiveCampaign account:

![image 2016-08-09 at 10 31 12 am](https://cloud.githubusercontent.com/assets/634489/17522419/965f4602-5e1c-11e6-93cf-ec74a75b556a.png)

**Comment by ninjasort** [comment]
Cool, thanks.
